# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84b53f7c1b3b02ca26e0fd1f37d3ee5e6c6e82304459214f654579e1fc3a0614fdde016a16ca3dec1083eb3cdf18bd994d5f7eb202bc0a10b4b67205eb96c1ff

test:
  secret_key_base: ddae08d0f02d814e344f5d5c9d76d84d8c9c1bec739b86a07c29a282eb12cada278659b0d1a151ade807f6f44844ae1c5bfc2b56278f846678278331b5e5fa93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
